### ISSUE TITLE
Fix Affected and Fixed Package information

### ISSUE THREAD

**Issue by taechae** [mchmarny/vulctl#32]

**Comment by taechae** [comment]
Fixed for Grype.

Trivy does not provide this information.

Looks like Snyk does provide the information in isUpgradable/isPatchable but cannot find an example with the information populated.

**Comment by mchmarny** [comment]
Looks like trivy CLI does not outputs that field, even when there are upgradable vulns. This won't help, but the [data/trivy.json](data/trivy.json) sample in the repo is now for the [Ruby app image](https://console.cloud.google.com/artifacts/docker/cloudy-build/us-west1/vulctl/ruby-demo/sha256:666b0f0498092184d635ac8fc53e30586f7bb8895e7ed8afba60632398c1af74;tab=vulnerabilities?project=cloudy-build) which has many fixable vuls.
