### ISSUE TITLE
Package type for Snyk and Trivvy not set

### ISSUE THREAD

**Issue by taechae** [mchmarny/vulctl#40]
Will default to OS

**Comment by mchmarny** [comment]
IN case of Trivy, there is the `Class` field on result that we could use

* `lang-pkgs` == `pkg`
* `os-pkgs` == `os`

Thoughts?

**Comment by mchmarny** [comment]
In case of Snyk, there is the `language` field which I assume when is `linux` then the type would be `os` but that doesn't seem to parse well given current samples.

**Comment by mchmarny** [comment]
PR #46 adds a generic package mapping
